=== Silox/UGent-stuff/ITech--Practicum-2/Practicum_2_Extras/21000-02.xsd
<?xml version="1.0"?>
<!--============================================================-->
<!--============================================================-->
<!--                                                            -->
<!--           Schema for DIDL XML Document Type                -->
<!--                                                            -->
<!--============================================================-->
<!--============================================================-->
<xsd:schema targetNamespace="urn:mpeg:mpeg21:2002:02-DIDL-NS" xmlns="urn:mpeg:mpeg21:2002:02-DIDL-NS" xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="0.01">
	<!--============================================================

	 Basic Principles that apply to all element types:

	 1) Any element with an attribute named 'id' of type ID may 
	    have a Reference child.

	 2) Elements with an attribute of type ID *may not* have any
	    attributes which are required.  This is because
	    attributes should be inheritable from a Reference
	    if they are not specified, which is not possible
	    if they are required. 

	 3) If an element has a Reference child 
	    then only Descriptor (and possibly Condition) elements may 
	    precede it, and no elements may follow it.

	============================================================-->
	<xsd:attributeGroup name="ID_ATTRS">
		<xsd:attribute name="id" type="xsd:ID" use="optional"/>
	</xsd:attributeGroup>
	<!--============================================================

	 DIDL element may contain exactly one Container or Item.

	============================================================-->
	<xsd:element name="DIDL">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Declarations" minOccurs="0"/>
				<xsd:choice>
					<xsd:element ref="Container"/>
					<xsd:element ref="Item"/>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 A Declarations element contains any number of Items, Descriptors,
	 Components, and Anchors, in any order.

	============================================================-->
	<xsd:element name="Declarations">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element ref="Item"/>
				<xsd:element ref="Descriptor"/>
				<xsd:element ref="Component"/>
				<xsd:element ref="Annotation"/>
				<xsd:element ref="Anchor"/>
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Container element may contain any number of Container elements
	 followed by any number of Items.

	============================================================-->
	<xsd:element name="Container">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:choice>
					<xsd:element ref="Reference"/>
					<xsd:sequence>
						<xsd:element ref="Container" minOccurs="0" maxOccurs="unbounded"/>
						<xsd:element ref="Item" minOccurs="0" maxOccurs="unbounded"/>
					</xsd:sequence>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attributeGroup ref="ID_ATTRS"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Item element contains any number Choice elements,
	 followed by at least one Item or Component element.
	 An Item can be conditional.

	============================================================-->
	<xsd:element name="Item">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Condition" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Choice" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:choice>
					<xsd:element ref="Reference"/>
					<xsd:choice minOccurs="0" maxOccurs="unbounded">
						<xsd:element ref="Item"/>
						<xsd:element ref="Component"/>
					</xsd:choice>
				</xsd:choice>
				<xsd:element ref="Annotation" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attributeGroup ref="ID_ATTRS"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 A Descriptor contains descriptive data about its parent
	 element.

	 The Descriptor can be resource-based (comprised of a single 
	 Component), or text-based (comprised of a single Statement).
	 A Descriptor can be conditional.
	
	============================================================-->
	<xsd:element name="Descriptor">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Condition" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:choice>
					<xsd:element ref="Reference"/>
					<xsd:element ref="Component"/>
					<xsd:element ref="Statement"/>
				</xsd:choice>
			</xsd:sequence>
			<xsd:attributeGroup ref="ID_ATTRS"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 A Statement contains descriptive data within a 
	 Descriptor. 

	 Attribs: 
	 mimeType  - A string identifying the type of metadata
	 ref  - A URI from which the metadata can be obtained
	 localPath - Specifies the required relative location for a cached version
	 encoding - Specifies the encoding format of the statement

	============================================================-->
	<xsd:element name="Statement">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:any namespace="##any" processContents="lax" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="mimeType" type="xsd:string" use="required"/>
			<xsd:attribute name="ref" type="xsd:anyURI"/>
			<xsd:attribute name="localPath" type="xsd:anyURI"/>
			<xsd:attribute name="encoding" type="xsd:string"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Component element contains one or more Resource elements, followed by any 
	 number of Anchor elements.
	 A Component can be conditional.

	============================================================-->
	<xsd:element name="Component">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Condition" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:choice>
					<xsd:element ref="Reference"/>
					<xsd:element ref="Resource" maxOccurs="unbounded"/>
				</xsd:choice>
				<xsd:element ref="Anchor" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attributeGroup ref="ID_ATTRS"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 An Anchor element indicates a point of interest in the
	 resource of the parent Component.
	 An Anchor can be conditional.
	
	 Attribs:
	 precedence  - An unsigned integer value indicating the 
	               relative ranking of this Anchor among 
	               the other anchors in an Item.  The highest
	               precedence anchor is the default entry 
	               point.

	 fragment  - The fragment identifier that locates the part
	             of interest within the associated resource. This
	             string, when appended to the SRC attribute
	             of the parent, plus a '#', becomes the full
	             URI for the part of interest.

	============================================================-->
	<xsd:element name="Anchor">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Condition" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Reference" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="precedence" type="xsd:unsignedInt"/>
			<xsd:attribute name="fragment" type="xsd:string"/>
			<xsd:attributeGroup ref="ID_ATTRS"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Condition element contains no children.  It indicates a
	 selection condition for the parent file.  Multiple Condition
	 tags indicate an 'OR' relationship, in that only one Condition
	 needs to be satisfied for the parent element to be retrieved,
	 included, etc.  The individual IDs in the require attribute of
	 a Condition tag have an 'AND' relationship in that selection
	 of all of the IDs referenced are required to satisfy that
	 Condition.

	 Attribs:
	 require   - Indicates the Selection(s) that must be affirmed 
	             for this Condition to be "satisfied".

	 except    - Indicates the Selection(s) that must be denied 
	             for this Condition to be "satisfied".

	============================================================-->
	<xsd:element name="Condition">
		<xsd:complexType>
			<xsd:attribute name="require" type="xsd:IDREFS"/>
			<xsd:attribute name="except" type="xsd:IDREFS"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Choice element contains one or more Selections.  
	 A Choice can be conditional.
	 
	 Attribs:

	 minSelections   - Minimum number of Selections that must be made. If 
	                   not present, there is no minimum.

	 maxSelections   - Maximum number of Selections that can be made. If 
	                   not present, there is no maximum.

	 default   - Indicates one or more default selections to use in the absence
	             of info to make a more specific decision.  Must conform to the
	             requirements of the minSelections and/or maxSelections
	             attributes if present.

	 choice_id   - Serves as a target for Assertion elements.

	============================================================-->
	<xsd:element name="Choice">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Condition" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Selection" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="minSelections" type="xsd:nonNegativeInteger"/>
			<xsd:attribute name="maxSelections" type="xsd:positiveInteger"/>
			<xsd:attribute name="default" type="xsd:IDREFS"/>
			<xsd:attribute name="choice_id" type="xsd:ID"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Selection element contains no children.
	 A Selection can be conditional.

	 Attrib: select_id - Uniquely identifies the Selection

	============================================================-->
	<xsd:element name="Selection">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Condition" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="select_id" type="xsd:ID" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Resource element contains or points to resource data.

	 Attribs: 
	 mimeType  - An identifier of a recognized scheme indicating the type
	             of the resource.
	 ref  - A URI from which the resource data can be obtained
	 localPath - Specifies the required relative location for a cached version
	 encoding - Specifies the encoding format of the resource

	============================================================-->
	<xsd:element name="Resource">
		<xsd:complexType mixed="true">
			<xsd:sequence>
				<xsd:any namespace="##any" processContents="lax" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="mimeType" type="xsd:string" use="required"/>
			<xsd:attribute name="ref" type="xsd:anyURI"/>
			<xsd:attribute name="localPath" type="xsd:anyURI"/>
			<xsd:attribute name="encoding" type="xsd:string"/>
		</xsd:complexType>
		<!-- "mixed" content model allows for embedded resources -->
	</xsd:element>
	<!--============================================================
	 
	 Reference contains no child elements				

	 Attrib: target - Points to the referenced element

	============================================================-->
	<xsd:element name="Reference">
		<xsd:complexType>
			<xsd:attribute name="target" type="xsd:anyURI" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Annotation contains any number of Assertions followed by 
	 any number of Descriptors followed by any number of Anchors			

	 Attrib: target - Points to the element being annotated

	 Restrictions: 
		1. The target must reference an element within the
		   parent Item, or can reference the parent Item itself.
		2. The contents of an Annotation must conform with the 
		   content model of the targeted element. For example,
		   Anchors can be included only if the target references
		   a Component.

	============================================================-->
	<xsd:element name="Annotation">
		<xsd:complexType>
			<xsd:choice>
				<xsd:element ref="Reference"/>
				<xsd:sequence>
					<xsd:element ref="Assertion" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="Descriptor" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="Anchor" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:choice>
			<xsd:attribute name="target" type="xsd:anyURI"/>
			<xsd:attributeGroup ref="ID_ATTRS"/>
		</xsd:complexType>
	</xsd:element>
	<!--============================================================

	 Assertion contains no child elements

	 Attribs: 

		target – identifies the Choice that this Assertion affects
		true   - The set of selection IDs which are asserted as true
		false  - The set of selection IDs which are asserted as false

	============================================================-->
	<xsd:element name="Assertion">
		<xsd:complexType>
			<xsd:attribute name="target" type="xsd:anyURI" use="required"/>
			<xsd:attribute name="true" type="xsd:NMTOKENS" use="optional"/>
			<xsd:attribute name="false" type="xsd:NMTOKENS" use="optional"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== Silox/UGent-stuff/ITech--Practicum-2/opgave-2-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<DIDL xmlns="urn:mpeg:mpeg21:2002:02-DIDL-NS"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:mpeg:mpeg21:2002:02-DIDL-NS
      http://vstudent.elis.ugent.be/itech/bestanden/21000-02.xsd">
  
	<Item>
		<Descriptor>
			<Statement mimeType="text/plain">DID voor een filmcollectie (groep 1)</Statement>
		</Descriptor>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Black Hawk Down</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/black_hawk_down.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:black_hawk_down"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Brotherhood of the Wolf</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/brotherhood_of_the_wolf.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:brotherhood_of_the_wolf"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Charlie Chocolate</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/charlie_chocolate.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:charlie_chocolate"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Constantine</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/constantine.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:constantine"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Corpse Bride</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/corpse_bride.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:corpse_bride"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Day after Tomorrow</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/day_after_tomorrow.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:day_after_tomorrow"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Finding Neverland</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/finding_neverland.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:finding_neverland"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">House of Flying Daggers</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/flying_daggers.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:flying_daggers"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Harry Potter and the Prisoner of Azkaban</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/harry_potter_azkaban.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:harry_potter_azkaban"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Ice Age</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/ice_age.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:ice_age"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Kingdom of Heaven</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/kingdom_of_heaven.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:kingdom_of_heaven"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Monsters Inc.</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/monsters_inc.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:monsters_inc"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Lord of the Rings: the Return of the King</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/return_of_the_king.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:return_of_the_king"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Sin City</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/sin_city.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:sin_city"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">The Aviator</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/the_aviator.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:the_aviator"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">The Merchant of Venice</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/the_merchant_of_venice.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:the_merchant_of_venice"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">The New World</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/the_new_world.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:the_new_world"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Underworld</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/underworld.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:underworld"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">Van Helsing</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/van_helsing.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:van_helsing"/>
			</Component>
		</Item>

		<Item>
			<Descriptor>
				<Statement mimeType="text/plain">War of the Worlds</Statement>
			</Descriptor>
			<Descriptor>
				<Component>
					<Resource mimeType="image/jpg" ref="http://multimedialab.elis.ugent.be/posters/war_of_the_worlds.jpg"/>
				</Component>
			</Descriptor>
			<Component>
				<Resource mimeType="video/x-ms-wmv" ref="urn:mpeg:mpeg21:be:ugent:mmlab:trailers:war_of_the_worlds"/>
			</Component>
		</Item>
	</Item>
</DIDL>
